# Instalación de Git y Bash

Para participar en este taller necesitas acceso al siguiente software y acceso a un navegador como chrome o firefox.

## Windows

**Nota:** Para obtener más detalles sobre cómo instalar y configurar Git Bash, puedes ver este video tutorial: [Cómo instalar Git en Windows 11 (Actualizado 2025)](https://www.youtube.com/watch?v=t2-l3WvWvqg).

1.  Descarga el instalador de [Git para Windows](https://gitforwindows.org/).

2.  Ejecuta el instalador y sigue los siguientes pasos:

    -   Haz clic en **"Next" cuatro veces** (dos veces si ya has instalado Git previamente). No necesitas cambiar nada en las pantallas de Información, ubicación, componentes y menú de inicio.

    -   En el menú desplegable **"Choosing the default editor used by Git", selecciona "Use the Nano editor by default"** (NOTA: necesitarás desplazarte hacia arriba para encontrarlo) y haz clic en "Next".

    -   En la página que dice **"Adjusting the name of the initial branch in new repositories", asegúrate de que "Let Git decide"** esté seleccionado. Esto garantizará el nivel más alto de compatibilidad para nuestras lecciones.

    -   Asegúrate de que esté seleccionada la opción **"Git from the command line and also from 3rd-party software" y haz clic en "Next".** (Si no haces esto, Git Bash no funcionará correctamente, lo que te obligará a eliminar la instalación de Git Bash, volver a ejecutar el instalador y seleccionar la opción "**Git from the command line and also from 3rd-party software").**

    -   Selecciona **"Use bundled OpenSSH"**.

    -   Asegúrate de que **"Use the native Windows Secure Channel Library" esté seleccionada y haz clic en "Next"**.

    -   Asegúrate de que **"Checkout Windows-style, commit Unix-style line endings" esté seleccionada y haz clic en "Next".**

    -   Asegúrate de que **"Use Windows' default console window"** esté seleccionada y haz clic en "Next".

    -   Asegúrate de que **"Default (fast-forward or merge)"** esté seleccionada y haz clic en "Next".

    -   Asegúrate de que **"Git Credential Manager"** esté seleccionada y haz clic en "Next".

    -   Asegúrate de que **"Enable file system caching"** esté seleccionada y haz clic en "Next".

    -   Haz clic en **"Install"**.

    -   Haz clic en **"Finish" o "Next"**.

3.  Si tu variable de entorno **"HOME"** no está configurada (o no sabes qué es):

-   Abre el símbolo del sistema (abre el menú de inicio, luego escribe `cmd` y presiona **Enter**).
-   Escribe la siguiente línea exactamente como se muestra en la ventana del símbolo del sistema.

``` {.bash eval="false"}
setx HOME "%USERPROFILE%"
```

-   Presiona Enter, deberías ver "SUCCESS: Specified value was saved".
-   Cierra el símbolo del sistema escribiendo "exit" y presionando Enter.

Esto te proporcionará tanto Git como Bash en el programa **Git Bash**.

## macOS

En macOS, el shell por defecto en la mayoría de las versiones es **Bash**, por lo que no es necesario instalarlo Puedes acceder a Bash desde la aplicación **Terminal**, ubicada en **/Applications/Utilities/**\

**Nota:** Para obtener más detalles sobre cómo instalar y configurar Git Bash, puedes ver este video tutorial: [Instalar Git fácilmente en MacOS 2025](https://www.youtube.com/watch?v=kdM9YOX2hZ0)\

En el sitio oficial de [git](https://git-scm.com/install/mac) existen varias opciones para la instalación en macOS, en este caso se llevará a cabo a través de [**Homebrew**](https://brew.sh/).

1.  Instalar Homebrew (en caso de que no esté instalado)

    -   Busca y abre la aplicación de la terminal en tu computadora

    -   Copia y pega el siguiente código en la terminal y presiona **Enter**

        `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

    -   Presiona **Enter** para comenzar la instalación

    -   Una vez que acabe la instalación, verifica que la instalación se haya llevado a cabo correctamente con el siguiente código:

        `brew --version`

        Después de presionar **Enter** aparecerá la última versión de **Homebrew** `Homebrew 4.5.7`

2.  Una vez instalado **Homebrew** copia y pega el siguiente código en la terminal

    `brew install git`

    Presiona **Enter**

Se recomienda mantener la Terminal anclada en el Dock para facilitar su uso durante el taller

## Linux

La mayoría de las distribuciones de **Linux** incluyen **Bash** como shell predeterminado y **Git** instalado por defecto.\

Si tu sistema es diferente, abre una terminal y ejecuta el comando:

`bash`

## Material suplementario

-   Tutorial: Nelly Selem -- [Bioinformática](#0)
-   En Windows puedes usar [Git Bash](https://miguel-mx.github.io/2024-01-24-ccm-unam-swc/) como entorno de práctica
